# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='book_copy',
            new_name='book_copy_id',
        ),
    ]
