# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20180915_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(blank=True),
        ),
    ]
