# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_auto_20180916_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_year',
            new_name='publish_date',
        ),
    ]
