# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_auto_20180916_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
