# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_author_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='years_of_life',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
