# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_auto_20180916_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
