# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_remove_book_add_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
