# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0015_auto_20180922_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 12, 14, 34, 53, 578288)),
        ),
    ]
