# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0016_auto_20181013_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 12, 14, 36, 4, 909864)),
        ),
    ]
