# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0018_auto_20181013_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_borrowed',
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_librarian',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='borrow',
            name='receive_librarian',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 26, 15, 5, 16, 84410)),
        ),
    ]
