# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 12:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0025_auto_20181027_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('receive_date', models.DateField()),
                ('book_copy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.BookCopy')),
                ('borrow_librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_borrow_librarian', to=settings.AUTH_USER_MODEL)),
                ('receive_librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_receive_librarian', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 27, 13, 7, 55, 615653)),
        ),
    ]
