# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0028_auto_20181028_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_copy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_bookcopy', to='library_app.BookCopy'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 30, 23, 44, 18, 834148)),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
