# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0029_auto_20181031_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 30, 23, 46, 25, 190713)),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
