# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0032_auto_20181102_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 2, 11, 47, 38, 340790)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='post_code',
            field=models.CharField(max_length=6),
        ),
    ]
