# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0033_auto_20181103_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 2, 11, 50, 36, 972899)),
        ),
    ]
