# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 15:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0035_auto_20181103_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='can_borrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Miejsce urodzenia'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Adres url portretu, zakończony rozszerzeniem'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='author',
            name='years_of_life',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Lata życia'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book_authors', to='library_app.Author', verbose_name='Autorzy'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_categories', to='library_app.Category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(default=1, verbose_name='Numer wydania'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Adres url okładki zakończony rozszerzeniem obrazu'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, unique=True, verbose_name='Numer ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_houses', to='library_app.PublishingHouse', verbose_name='Wydawnictwo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcopies', to='library_app.Book', verbose_name='Wybierz książkę'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book_copy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_bookcopy', to='library_app.BookCopy', verbose_name='Egzemplarz ksiązki'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(auto_now=True, verbose_name='Data wypożyczenia'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_librarian', to=settings.AUTH_USER_MODEL, verbose_name='Bibliotekarz wypożyczający'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 9, 16, 11, 47, 394633), verbose_name='Data oddania'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_librarian', to=settings.AUTH_USER_MODEL, verbose_name='Bibliotekarz odbierający'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wypożycz dla'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Nazwa kategorii'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='city',
            field=models.CharField(max_length=300, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='house_number',
            field=models.CharField(max_length=20, verbose_name='Numer domu'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='postal_code',
            field=models.CharField(max_length=9, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='street',
            field=models.CharField(max_length=300, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='house_number',
            field=models.CharField(max_length=20, verbose_name='Numer domu'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='pesel',
            field=models.CharField(max_length=11, verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='post_code',
            field=models.CharField(max_length=6, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='street',
            field=models.CharField(max_length=200, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
