# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0036_auto_20181110_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='is_prolong',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 9, 17, 27, 16, 19790), verbose_name='Data oddania'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='can_borrow',
            field=models.BooleanField(default=True, verbose_name='Czy może wypożyczać?'),
        ),
    ]
