# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0037_auto_20181110_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='is_prolong',
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_prolong',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 9, 17, 35, 54, 894890), verbose_name='Data oddania'),
        ),
    ]
