# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0039_auto_20181111_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='have_borrows_with_exceeded_date',
            field=models.BooleanField(default=False, verbose_name='Czy ma egzemplarze z przekroczoną datą oddania?'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='is_date_exceeded',
            field=models.BooleanField(default=False, verbose_name='Czy data oddania przekroczona'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='is_prolong',
            field=models.BooleanField(default=False, verbose_name='Czy prolongowana'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 10, 17, 44, 28, 69596), verbose_name='Data oddania'),
        ),
    ]
