# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0040_auto_20181111_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='have_borrows_with_exceeded_date',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 20, 17, 25, 33, 528563), verbose_name='Data oddania'),
        ),
    ]
