# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0042_auto_20181128_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(default='', max_length=200, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 27, 16, 55, 30, 672720), verbose_name='Data oddania'),
        ),
    ]
