# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0043_auto_20181128_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 2, 12, 9, 40, 255411), verbose_name='Data oddania'),
        ),
    ]
