# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0045_auto_20190101_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(auto_now=True, verbose_name='Data wypożyczenia'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='receive_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 2, 20, 26, 2, 666691), verbose_name='Data oddania'),
        ),
    ]
